Update archiveloop
Archive will always be reachable, disable check

diff --git a/run/archiveloop b/run/archiveloop
--- a/run/archiveloop
+++ b/run/archiveloop
@@ -232,11 +232,11 @@ function wait_for_archive_to_be_unreachable () {
   log "Waiting for archive to be unreachable..."
   while true
     do
-      if ! retry archive_is_reachable
-      then
-        log "Archive is unreachable."
-        break
-      fi
+#      if ! retry archive_is_reachable
+#      then
+#        log "Archive is unreachable."
+#        break
+#      fi
       if [ -e /tmp/archive_is_unreachable ]
       then
         log "Simulating archive being unreachable."
